return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = { "BufReadPre", "BufNewFile" },
  opts = {
    ensure_installed = {
      "go",
      "gomod",
      "gosum",
      "typescript",
      "tsx",
      "javascript",
      "vue",
      "svelte",
      "lua",
      "vim",
      "vimdoc",
      "markdown",
      "markdown_inline",
      "html",
      "css",
      "json",
      "yaml",
      "toml",
      "bash",
      "regex",
      "diff",
      "gitcommit",
    },
    highlight = { enable = true },
    indent = { enable = true },
    auto_install = true,
  },
}
